import { defineTable } from "convex/server";
import { v } from "convex/values";
import {
  root,
  target,
  provenance,
  roleFacts,
  entityFacts,
  arrangementFacts,
  assignmentFacts,
  template,
} from "./shared";
const segment = <T extends Parameters<typeof v.object>[0]>(facts: T) =>
  v.object({
    valid_from: v.number(),
    valid_to: v.optional(v.number()),
    facts: v.object(facts),
  });
export const foundationSchema = {
  entity_revision: defineTable({
    user_id: v.string(),
    root_id: v.id("entity"),
    revision: v.number(),
    ...provenance,
    prior_id: v.optional(v.id("entity_revision")),
    segments: v.array(segment(entityFacts)),
  }).index("by_root", ["root_id"]),
  arrangement_revision: defineTable({
    user_id: v.string(),
    root_id: v.id("arrangement"),
    revision: v.number(),
    ...provenance,
    prior_id: v.optional(v.id("arrangement_revision")),
    segments: v.array(segment(arrangementFacts)),
  }).index("by_root", ["root_id"]),
  arrangement_type: defineTable({
    ...root,
    name: v.string(),
    revision: v.number(),
    templates: v.array(template),
  }).index("by_user", ["user_id"]),
  arrangement_type_revision: defineTable({
    user_id: v.string(),
    root_id: v.id("arrangement_type"),
    revision: v.number(),
    ...provenance,
    name: v.string(),
    templates: v.array(template),
  }).index("by_root", ["root_id"]),
  arrangement_role_definition: defineTable({
    ...root,
    arrangement_id: v.id("arrangement"),
    ...roleFacts,
    revision: v.number(),
    template_revision_id: v.optional(v.id("arrangement_type_revision")),
    template_index: v.optional(v.number()),
  }).index("by_arrangement", ["arrangement_id"]),
  role_definition_revision: defineTable({
    user_id: v.string(),
    root_id: v.id("arrangement_role_definition"),
    revision: v.number(),
    ...provenance,
    segments: v.array(segment(roleFacts)),
  }).index("by_root", ["root_id"]),
  arrangement_role_assignment: defineTable({
    ...root,
    arrangement_id: v.id("arrangement"),
    role_definition_id: v.id("arrangement_role_definition"),
    ...assignmentFacts,
    revision: v.number(),
    legacy_role_id: v.optional(v.id("arrangement_role")),
    history_unknown: v.optional(v.boolean()),
    legacy_share_json: v.optional(v.string()),
  })
    .index("by_role", ["role_definition_id"])
    .index("by_arrangement", ["arrangement_id"])
    .index("by_entity", ["entity_id"]),
  role_assignment_revision: defineTable({
    user_id: v.string(),
    root_id: v.id("arrangement_role_assignment"),
    revision: v.number(),
    ...provenance,
    segments: v.array(segment(assignmentFacts)),
  }).index("by_root", ["root_id"]),
  ownership_interest: defineTable({
    ...root,
    owner_entity_id: v.id("entity"),
    asset_entity_id: v.id("entity"),
    arrangement_id: v.id("arrangement"),
    assignment_id: v.optional(v.id("arrangement_role_assignment")),
    basis: v.string(),
    share_bps: v.number(),
    valid_from: v.number(),
    valid_to: v.optional(v.number()),
  }).index("by_asset", ["asset_entity_id"]),
  tag: defineTable({ ...root, name: v.string() }).index("by_user", ["user_id"]),
  tag_assignment: defineTable({
    user_id: v.string(),
    tag_id: v.id("tag"),
    target,
    added_at: v.number(),
    removed_at: v.optional(v.number()),
  }).index("by_tag", ["tag_id"]),
  details_document: defineTable({
    user_id: v.string(),
    target,
    repository_key: v.string(),
    path: v.string(),
    observed_commit: v.optional(v.string()),
    availability: v.union(
      v.literal("available"),
      v.literal("missing"),
      v.literal("unreadable"),
    ),
    created_at: v.number(),
  }).index("by_user", ["user_id"]),
  evidence_item: defineTable({
    ...root,
    kind: v.string(),
    namespace: v.string(),
    external_key: v.optional(v.string()),
    source_date: v.optional(v.string()),
    captured_at: v.number(),
    content_ref: v.string(),
    supersedes_id: v.optional(v.id("evidence_item")),
  }).index("by_user", ["user_id"]),
  evidence_link: defineTable({
    user_id: v.string(),
    evidence_id: v.id("evidence_item"),
    target,
    target_revision: v.optional(v.number()),
    relationship: v.union(v.literal("supports"), v.literal("contradicts")),
    recorded_at: v.number(),
  }).index("by_evidence", ["evidence_id"]),
  migration_map: defineTable({
    source_table: v.string(),
    source_id: v.string(),
    target_table: v.string(),
    target_id: v.string(),
    migration: v.string(),
    recorded_at: v.number(),
  }).index("by_source", ["source_table", "source_id"]),
  migration_issue: defineTable({
    source_table: v.string(),
    source_id: v.string(),
    reason: v.string(),
    recorded_at: v.number(),
    resolved: v.optional(v.boolean()),
  }).index("by_source", ["source_table", "source_id"]),
};
